services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_conta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - conta_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_conta
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - conta_network

  php:
    build: .
    container_name: php_conta
    ports:
      - "8080:80"
    volumes:
      - ./conta:/var/www/html
    environment:
      DB_HOST: postgres
      DB_NAME: banco
      DB_USER: postgres
      DB_PASS: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - conta_network

volumes:
  postgres_data:

networks:
  conta_network:
    driver: bridge
